@localUrl = http://localhost:3001/api
@herokuUrl = idk

@baseUrl = {{localUrl}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0cmluZzExMjEyMTIiLCJpZCI6IjYyOTY0M2I2NTczYWUzYWFkZDgyN2VjZCIsImlhdCI6MTY1NDA4NzY5OH0.E4gsHj1vxbkli0eDbjmO9wWT0o6kB2UHV4fvDGtHHDA

## Get all blogs

GET {{baseUrl}}/blogs


### Create new blog

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 1
}
