@localUrl = http://localhost:3001/api
@herokuUrl = idk

@baseUrl = {{localUrl}}

## Get all blogs

GET {{baseUrl}}/blogs


### Create new blog

POST {{baseUrl}}/blogs
Content-Type: application/json

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 1
}
