@localUrl = http://localhost:3001/api
@herokuUrl = idk

@baseUrl = {{localUrl}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNzc3MiLCJpZCI6IjYyOTdiYzNiNDAxYWJiOWY3YzFlMTVhMCIsImlhdCI6MTY1NDExMTI5M30.uxOmslF29ZlJI7PVYQ0uhb0DgzeAx96TypL8ai3TLiI

@someId = 6297bcf67f24e2dff081f1ed
## Get all blogs

GET {{baseUrl}}/blogs


### Create new blog

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 1
}


### Delete a blog

DELETE {{baseUrl}}/blogs/{{someId}}
Content-Type: application/json
Authorization: bearer {{token}}
