@localUrl = http://localhost:3001/api
@herokuUrl = idk

@baseUrl = {{localUrl}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNzcyIsImlkIjoiNjI5NzY2NmViY2ExMThmMzlhOTUwOGRkIiwiaWF0IjoxNjU0MTEyMDIwfQ.NCijKDl60KYWQZdRTeU_46dAyNo24iqw58tQP1fPqW0

@someId = 6294cfd536ee37f0bc1d95b5
## Get all blogs, needs token which kinda sucks

GET {{baseUrl}}/blogs
Authorization: bearer {{token}}

### Create new blog

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 1
}

### Add a comment

POST {{baseUrl}}/blogs/{{someId}}/comments
Content-Type: application/json

{
    "comment": "This is a comment!"
}


### Delete a blog

DELETE {{baseUrl}}/blogs/{{someId}}
Content-Type: application/json
Authorization: bearer {{token}}
