services:
  app:
    extends:
      file: ./frontend/docker-compose.yml
      service: app
  server:
    extends:
      file: ./backend/docker-compose.yml
      service: server
  mongo:
    extends:
      file: ./backend/docker-compose.yml
      service: mongo
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_dataa: