@url = http://localhost:3001/api

### Get all
GET {{url}}/patients

### Get spesific
GET {{url}}/patients/d2773598-f723-11e9-8f0b-362b9e155667

### Create new
POST {{url}}/patients
Content-Type: application/json

{
    "name": "new",
    "gender": "male",
    "occupation": "teacher",
    "ssn": "121212-121A",
    "dateOfBirth": "1991-12-12"
}

### Create new, invalid ssn

POST {{url}}/patients
Content-Type: application/json

{
    "name": "new",
    "gender": "male",
    "occupation": "teacher",
    "ssn": "121a21A",
    "dateOfBirth": "1991-12-12"
}

### Create new, invalid dob

POST {{url}}/patients
Content-Type: application/json

{
    "name": "new",
    "gender": "male",
    "occupation": "teacher",
    "ssn": "121212-121A",
    "dateOfBirth": "19911231adas2"
}

### Create new, missing field

POST {{url}}/patients
Content-Type: application/json

{
    "gender": "male",
    "occupation": "teacher",
    "ssn": "121212-121A",
    "dateOfBirth": "1991-12-12"
}


### Add entry

POST {{url}}/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "id": "37be178f-a432-4ba4-aac2-f86810e36a15",
    "date": "2018-10-05",
    "specialist": "MD House",
    "type": "HealthCheck",
    "description":
        "Yearly control visit. Due to high cholesterol levels recommended to eat more vegetables.",
    "healthCheckRating": 1
}